[project]
name = "strands-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "litellm>=1.74.8",
    "strands-agents>=1.1.0",
    "strands-agents-builder>=0.1.7",
    "strands-agents-tools>=0.2.2",
]
